# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: inklet 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "inklet"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Roman Shterenzon"]
  s.date = "2014-06-24"
  s.description = "Helpers for the Foundation Ink framework"
  s.email = "romanbsd@yahoo.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.homepage = "http://github.com/romanbsd/inklet"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Helpers for the Foundation Ink framework"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<actionpack>, ["< 5", "~> 3.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.14.1"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<actionpack>, ["< 5", "~> 3.2"])
      s.add_dependency(%q<rspec>, ["~> 2.14.1"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<actionpack>, ["< 5", "~> 3.2"])
    s.add_dependency(%q<rspec>, ["~> 2.14.1"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

